### ISSUE TITLE
Lyrics sometimes don't start playing

### ISSUE THREAD

**Issue by sassmann** [osdlyrics/osdlyrics#61]
After adding a few tracks to the playlist, the first track playing scrolls lyrics fine, but when press the "next track" button in about 80% of the time only the first lyric line shows up and never starts scrolling.

Debug log
https://paste.fedoraproject.org/paste/b5Eb-IVW6S6OU-gwcyLDQQ/raw

**Comment by pjw91** [comment]
Oops, please replace `logger` with `logging` in both `daemon/player.py` and `daemon/lyrics.py` and see if it works.

**Comment by sassmann** [comment]
That fixes some of the errors in the log but doesn't resolve the problem.
Here's a new log with the changes applied.
https://paste.fedoraproject.org/paste/JQwy-bgmhuAl83PPpNBnYg/raw

**Comment by pjw91** [comment]
Oops, I missed that Python2 needs another dependency `configparser` (apt-get install python-configparser or pip install configparser).

As we don't have a mechanism reporting all errors from Python, please:
1. `/usr/bin/python /usr/local/lib/osdlyrics/daemon/main.py`
2. then `osdlyrics`.

If there's something wrong in (1), please attach it. Otherwise, the errors reported by (1) are missing.

**Comment by sassmann** [comment]
python2-configparser is already installed.

main.py output on startup:
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpd: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.PlayerProxy.Mpd exited with status 1
but I guess that's harmless. No new errors are printed during playback.

When I close the media player the following error shows up.
ERROR:root:expand gg
Traceback (most recent call last):
  File "/usr/lib64/osdlyrics/daemon/lyrics.py", line 405, in _expand_patterns
    path = expand_path(path_pat, metadata)
  File "/usr/lib/python2.7/site-packages/osdlyrics/pattern.py", line 161, in expand_path
    raise PatternException('Location not found in metadata')
PatternException: Location not found in metadata

**Comment by pjw91** [comment]
Those are harmless.

The 2nd one occurs when a constructed lrc-file-finding-pattern needs corresponding metadata but that does not exist. (eg. A pattern `%n` needs track number. When that is not provided, this error is logged at `daemon/lyrics.py:407` then try next pattern at line 408.)

**Comment by PedroHLC** [comment]
@sassmann and @pjw91 is the main issue solved?

**Comment by sassmann** [comment]
Hi Pedro,
Fedora 32 dropped python2 support, so I can't get osdlyrics to work anymore.
Any plans to migrate to python3?

**Comment by PedroHLC** [comment]
Hi @sassmann, we already have Python 3 support on the main-branch.
Here's a working PKBUILD for arch:
https://lonewolf.pedrohlc.com/chaotic-aur/.backups/osdlyrics.PKGBUILD

**Comment by alexcustos** [comment]
I just wanted to confirm, the latest version (built from the master branch `OSD Lyrics 0.5.15-1-g33dc42a`) almost never starts scrolling lyrics of the next or selected track in the playlist, only stopping and starting the song helps. There are no errors or any other clues on what's wrong.
> Python 3.10.12, Ubuntu 22.04.4 LTS, VLC 3.0.16
