### ISSUE TITLE
Crash when opening Preferences

### ISSUE THREAD

**Issue by ReimuNotMoe** [osdlyrics/osdlyrics#68]
The program will crash when opening Preferences via tray icon.

It seems that the `lrc_color_str` is uninitialized here.

```
$ gdb osdlyrics
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from osdlyrics...done.
(gdb) r
Starting program: /usr/local/bin/osdlyrics 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee6af700 (LWP 116577)]
[New Thread 0x7fffedeae700 (LWP 116578)]
[New Thread 0x7fffed6ad700 (LWP 116579)]
*Error*: in function _sync_default_cb: ol_config_proxy.c[105]
Cannot set config default values: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
[New Thread 0x7fffeceac700 (LWP 116620)]

(OSD Lyrics:116573): Gtk-WARNING **: 19:20:45.690: Unable to locate theme engine in module_path: "adwaita",

(OSD Lyrics:116573): Gtk-WARNING **: 19:20:45.695: Unable to locate theme engine in module_path: "adwaita",
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value OSD/locked from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/display-mode-osd from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/display-mode-scroll from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/display-mode-osd from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/display-mode-scroll from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/notify-music from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
[Thread 0x7fffedeae700 (LWP 116578) exited]
*Error*: in function ol_lyric_source_list_sources: ol_lyric_source.c[465]
Fail to get lyric source list: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Config exited with status 1
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/notify-music from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/notify-music from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/notify-music from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/notify-music from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_lyric_source_list_sources: ol_lyric_source.c[465]
Fail to get lyric source list: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Config exited with status 1
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetBool failed. Cannot get value General/notify-music from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
[New Thread 0x7fffedeae700 (LWP 116701)]
[Thread 0x7fffedeae700 (LWP 116701) exited]
[New Thread 0x7fffedeae700 (LWP 116725)]
[New Thread 0x7fffdcc9b700 (LWP 116726)]
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetDouble failed. Cannot get value OSD/lrc-align-0 from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get: ol_config_proxy.c[501]
GetDouble failed. Cannot get value OSD/lrc-align-1 from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
*Error*: in function ol_config_proxy_get_str_list: ol_config_proxy.c[603]
GetStringList failed. Cannot get value OSD/active-lrc-color from config: Cannot invoke method; proxy is for a well-known name without an owner and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag

Thread 1 "osdlyrics" received signal SIGSEGV, Segmentation fault.
load_osd () at ol_option.c:741
741             GdkColor color = ol_color_to_gdk_color (ol_color_from_string (lrc_color_str[i]));
(gdb) bt
#0  0x0000555555570b09 in load_osd () at ol_option.c:741
#1  0x0000555555570b09 in ol_option_update_widget (widgets=0x5555557a5a20 <options>) at ol_option.c:693
#2  0x0000555555570b09 in ol_option_show () at ol_option.c:1723
#3  0x00007ffff656010d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff6572fce in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff657b685 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff657c09f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff0cd92b4 in  () at /usr/lib/x86_64-linux-gnu/libdbusmenu-gtk.so.4
#8  0x00007ffff656010d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff6572fce in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff657b685 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff657c09f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff0aba49a in dbusmenu_menuitem_handle_event () at /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4
#13 0x00007ffff0abb8c7 in  () at /usr/lib/x86_64-linux-gnu/libdbusmenu-glib.so.4
#14 0x00007ffff6286c03 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff6286185 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff6286550 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff6286862 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff78c2a37 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#19 0x000055555556921a in main (argc=<optimized out>, argv=<optimized out>) at ol_main.c:919
(gdb) p lrc_color_str 
$1 = (char **) 0x0
(gdb)
```

**Comment by PedroHLC** [comment]
Hi @ReimuNotMoe.
Sorry for the late response, which version of Ubuntu and OSDLyrics are you using?
Could you try compiling the latest branch with python3 set in PYTHON envvar?

If this is no longer of your interest, please close the issue.
