### ISSUE TITLE
MPRIS2 needs some polishing

### ISSUE THREAD

**Issue by sassmann** [osdlyrics/osdlyrics#76]
Opening issue as suggested by Pedro.

```
$ osdlyrics
*Error*: in function _start_daemon_cb: ol_main.c[768]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

dbus log:
```
error time=1585928309.241087 sender=:1.96 -> destination=:1.20 error_name=org.freedesktop.DBus.Python.AttributeError reply_serial=445
   string "Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python3.8/site-packages/osdlyrics/dbusext/service.py", line 175, in GetAll
    ret[prop_name] = prop.__get__(self)
  File "/usr/local/lib/python3.8/site-packages/osdlyrics/dbusext/property.py", line 93, in __get__
    return wrap_dbus_type(self._type_signature, self._fget(obj))
  File "/usr/local/lib/osdlyrics/daemon/player.py", line 374, in Rate
    return self._player.Get(MPRIS2_PLAYER_INTERFACE, 'Rate')
AttributeError: 'NoneType' object has no attribute 'Get'
"
method return time=1585928309.241663 sender=:1.96 -> destination=:1.20 serial=27 reply_serial=448
   array [
      dict entry(
         string "CanQuit"
         variant             boolean false
      )
      dict entry(
         string "Fullscreen"
         variant             boolean false
      )
      dict entry(
         string "CanSetFullscreen"
         variant             boolean false
      )
      dict entry(
         string "CanRaise"
         variant             boolean false
      )
      dict entry(
         string "HasTrackList"
         variant             boolean false
      )
      dict entry(
         string "Identity"
         variant             string "OSD Lyrics"
      )
      dict entry(
         string "DesktopEntry"
         variant             string "osdlyrics"
      )
      dict entry(
         string "SupportedUriSchemes"
         variant             array [
            ]
      )
      dict entry(
         string "SupportedMimeTypes"
         variant             array [
            ]
      )
   ]
error time=1585928309.242553 sender=:1.96 -> destination=:1.20 error_name=org.freedesktop.DBus.Python.AttributeError reply_serial=449
   string "Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/local/lib/python3.8/site-packages/osdlyrics/dbusext/service.py", line 175, in GetAll
    ret[prop_name] = prop.__get__(self)
  File "/usr/local/lib/python3.8/site-packages/osdlyrics/dbusext/property.py", line 93, in __get__
    return wrap_dbus_type(self._type_signature, self._fget(obj))
  File "/usr/local/lib/osdlyrics/daemon/player.py", line 374, in Rate
    return self._player.Get(MPRIS2_PLAYER_INTERFACE, 'Rate')
AttributeError: 'NoneType' object has no attribute 'Get'
"
signal time=1585928309.242577 sender=:1.96 -> destination=(null destination) serial=29 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=PropertiesChanged
   string "org.mpris.MediaPlayer2.Player"
   array [
      dict entry(
         string "LoopStatus"
         variant             string "None"
      )
      dict entry(
         string "PlaybackStatus"
         variant             string "Stopped"
      )
      dict entry(
         string "Metadata"
         variant             array [
            ]
      )
      dict entry(
         string "Shuffle"
         variant             boolean false
      )
   ]
   array [
   ]

```

**Comment by kbsky** [comment]
Going through open bugs... I suspect the spat in D-Bus is just a consequence of the service not starting for whatever reason, is it something that is still reproducible?
