### ISSUE TITLE
PPA (.deb file) for Ubuntu 20.04

### ISSUE THREAD

**Issue by anishmittal2020** [osdlyrics/osdlyrics#77]
I tried to build the app from source and I am having issues when I am running it

```bash
$ osdlyrics
*Error*: in function _start_daemon_cb: ol_main.c[768]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1
```

- Also, I saw that Ubuntu PPA is not updated anymore, may I request you to please update it as majority of Linux users use Ubuntu and it would be so convenient for so many people.

- Not asking you to release PPA for every Ubuntu release, but it would be great if it can be released for every LTS version, that is once in two years.

- Or we could use a `.deb` file, for installation. The deb on this location: [Debian -- Details of package osdlyrics in sid](https://packages.debian.org/sid/osdlyrics) gives this error

```bash
$ sudo gdebi osdlyrics_0.5.5_rc1+dfsg1-2_amd64\ \(1\).deb 
[sudo] password for anish: 
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libc6 (>= 2.29)
```

**Comment by PedroHLC** [comment]
Seems like Ubuntu 20.04 has incorporated Debians' .deb in Ubuntu Universe. So closing this...

**Comment by anishmittal2020** [comment]
@PedroHLC I installed it as you said, but it is not starting:

```bash
$ osdlyrics -v
OSD Lyrics 0.5.0-git

$ osdlyrics
*Error*: in function _start_daemon_cb: ol_main.c[768]
Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1
```

**Comment by PedroHLC** [comment]
Please, gimme the output of: `python /usr/lib/osdlyrics/daemon/main.py` (or python3, not sure how it's called in Ubuntu)

**Comment by anishmittal2020** [comment]
I did what you said, and I got the error: `ModuleNotFoundError: No module named 'pycurl'`, so I insatlled it as follows, and then run the command again, but I get the same error!

```
$ pip3 install pycurl
Collecting pycurl
  Downloading pycurl-7.43.0.6.tar.gz (222 kB)
     |████████████████████████████████| 222 kB 5.6 MB/s 
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py) ... done
  Created wheel for pycurl: filename=pycurl-7.43.0.6-cp39-cp39-linux_x86_64.whl size=324900 sha256=7039a40af0e052f508ed530554fc8102e41f6eabef86e27815cbf373e048edbc
  Stored in directory: /home/nikhil/.cache/pip/wheels/86/d9/59/fe1c78371d31ef78f05972bb1b806afba47c5e6bd139f76302
Successfully built pycurl
Installing collected packages: pycurl
Successfully installed pycurl-7.43.0.6
```

```
$ python3 /usr/lib/osdlyrics/daemon/main.py
Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 34, in <module>
    import lyrics
  File "/usr/lib/osdlyrics/daemon/lyrics.py", line 43, in <module>
    import lrcdb
  File "/usr/lib/osdlyrics/daemon/lrcdb.py", line 31, in <module>
    import osdlyrics.utils
  File "/usr/lib/python3/dist-packages/osdlyrics/utils.py", line 33, in <module>
    import pycurl
ModuleNotFoundError: No module named 'pycurl'
```

**Comment by PedroHLC** [comment]
Install this one instead: https://launchpad.net/ubuntu/+source/pycurl

**Comment by anishmittal2020** [comment]
After install what you said: `$ sudo apt install python3-pycurl`

```bash
$ python3 /usr/lib/osdlyrics/daemon/main.py
Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 34, in <module>
    import lyrics
  File "/usr/lib/osdlyrics/daemon/lyrics.py", line 43, in <module>
    import lrcdb
  File "/usr/lib/osdlyrics/daemon/lrcdb.py", line 31, in <module>
    import osdlyrics.utils
  File "/usr/lib/python3/dist-packages/osdlyrics/utils.py", line 33, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time version (7.68.0) is older than compile-time version (7.73.0)
```

**Comment by PedroHLC** [comment]
Which ubuntu version are you using?

**Comment by anishmittal2020** [comment]
OS: Ubuntu 20.04.1 LTS x86_64

**Comment by anishmittal2020** [comment]
@PedroHLC Any update on this please?

**Comment by PedroHLC** [comment]
@anishmittal2020 I'm not part of the OSD-Lyrics team in Launchpad (Cc @tigersoldier).

Does the latest deb from Debian-Sid give you the same error?

**Comment by tigersoldier** [comment]
@PedroHLC I suggest creating a new PPA under the osdlyrics team. The previous PPA is under my personal account. I can't figure out how to transfer it.
