### ISSUE TITLE
*Error*: in function _start_daemon_cb: ol_main.c[768] Unable to start daemon: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Daemon exited with status 1

### ISSUE THREAD

**Issue by antizo** [osdlyrics/osdlyrics#78]
ubuntu20.04
`$ pip3 list
Package                Version      
---------------------- -------------
aiohttp                3.6.2        
apturl                 0.5.2        
async-timeout          3.0.1        
attrs                  19.3.0       
blinker                1.4          
Brlapi                 0.7.0        
certifi                2019.11.28   
chardet                3.0.4        
chrome-gnome-shell     0.0.0        
command-not-found      0.3          
cryptography           2.8          
cupshelpers            1.0          
dbus-python            1.2.16       
defer                  1.0.6        
distro                 1.4.0        
distro-info            0.23ubuntu1  
entrypoints            0.3          
future                 0.18.2       
gobject                0.1.0        
httplib2               0.14.0       
idna                   2.8          
iso8601                0.1.12       
keyring                18.0.1       
language-selector      0.1          
launchpadlib           1.10.13      
lazr.restfulclient     0.14.2       
lazr.uri               1.0.3        
louis                  3.12.0       
m3u8                   0.6.0        
macaroonbakery         1.3.1        
multidict              4.7.6        
netifaces              0.10.4       
oauthlib               3.1.0        
olefile                0.46         
pexpect                4.6.0        
Pillow                 7.0.0        
pip                    20.0.2       
protobuf               3.6.1        
pycairo                1.16.2       
pycryptodome           3.9.7        
pycups                 1.9.73       
pycurl                 7.43.0.5     
pydbus                 0.6.0        
PyGObject              3.36.0       
PyJWT                  1.7.1        
pymacaroons            0.13.0       
PyNaCl                 1.3.0        
pyRFC3339              1.1          
python-apt             2.0.0        
python-dateutil        2.7.3        
python-debian          0.1.36ubuntu1
pytz                   2019.3       
pyxattr                0.6.1        
pyxdg                  0.26         
PyYAML                 5.3.1        
reportlab              3.5.34       
requests               2.22.0       
requests-unixsocket    0.2.0        
SecretStorage          2.3.1        
setuptools             45.2.0       
simplejson             3.16.0       
six                    1.14.0       
ssh-import-id          5.10         
systemd-python         234          
ubuntu-advantage-tools 20.3         
ubuntu-drivers-common  0.0.0        
ufw                    0.36         
unattended-upgrades    0.1          
urllib3                1.25.8       
wadllib                1.3.3        
wheel                  0.34.2       
xkit                   0.0.0        
yarl                   1.4.2        
ykdl                   1.6.3        
youtube-dl             2020.3.24    `

`$ osdlyrics-daemon 
Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 27, in <module>
    from osdlyrics import PACKAGE_VERSION
ModuleNotFoundError: No module named 'osdlyrics'
`

**Comment by PedroHLC** [comment]
Just so I know the context, did you build it from master?

**Comment by Prn-Ice** [comment]
I have the same error but osdlyrics-daemon reports a different error.
```sh
❯ osdlyrics-daemon
Traceback (most recent call last):
  File "/usr/lib/osdlyrics/daemon/main.py", line 21, in <module>
    from builtins import super
ImportError: No module named builtins
```

**Comment by snorez** [comment]
@Prn-Ice  Did you install python-future/python3-future package? Check [README-runtime-dependencies](https://github.com/osdlyrics/osdlyrics#runtime-dependencies)

**Comment by Prn-Ice** [comment]
I just installed python3-future, I still get the error, I haven't restarted though.

**Comment by Prn-Ice** [comment]
I Re-Installed from the ubuntu repos and it works fine, thanks.

**Comment by acassis** [comment]
I download the version from Ubuntu repository and got even more errors:

```
$ osdlyrics-daemon 
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Http: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.PlayerProxy.Http exited with status 1
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpd: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.PlayerProxy.Mpd exited with status 1
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpris1: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.PlayerProxy.Mpris1 exited with status 1
WARNING:root:Cannot activate proxy org.osdlyrics.PlayerProxy.Mpris2: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.PlayerProxy.Mpris2 exited with status 1
ERROR:root:Cannot activate config service
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.xiami: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.LyricSourcePlugin.xiami exited with status 1
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.viewlyrics: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.LyricSourcePlugin.viewlyrics exited with status 1
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.netease: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.LyricSourcePlugin.netease exited with status 1
WARNING:root:Cannot activate lyric source org.osdlyrics.LyricSourcePlugin.lrc123: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.LyricSourcePlugin.lrc123 exited with status 1
ERROR:dbus.proxies:Introspect error on org.osdlyrics.Config:/org/osdlyrics/Config: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Config exited with status 1
ERROR:dbus.proxies:Introspect error on org.osdlyrics.Config:/org/osdlyrics/Config: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.osdlyrics.Config exited with status 1
```

**Comment by snorez** [comment]
@acassis  This is a different error message, "Process org.osdlyrics.Config exited with status 1". Can you please provide some more details, like the package version, how you install it, what you did?

**Comment by zzugyl** [comment]
same error.
try reinstall 
still not work

**Comment by PedroHLC** [comment]
When you say, "same error", do you mean `No module named 'osdlyrics' `?

**Comment by chris4540** [comment]
Hi all,

I am installing osdlyrics from source on ubuntu 18.04. I think the configuration has a problem.

This is the configuration output:
```
checking for /usr/bin/python3 version... 3.6
checking for /usr/bin/python3 platform... linux
checking for /usr/bin/python3 script directory... ${prefix}/lib/python3.6/site-packages
checking for /usr/bin/python3 extension module directory... ${exec_prefix}/lib/python3.6/site-packages
```
While the below is python3.6 sys.paths output:
```
python3 -c "import sys; print(sys.path)"

['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
```

Therefore, we cannot import osdlyrics on ubuntu platform

**Comment by PedroHLC** [comment]
Hi @chris4540, could you send a PR fixing it? This project doesn't have contributors anymore :sweat_smile:

**Comment by chris4540** [comment]
> Hi @chris4540, could you send a PR fixing it? This project doesn't have contributors anymore 
> 
> **EDIT**: Also, debian/ubuntu seems to have some patches for it, I would love to take those in!

Hej,
I would like to do so yet I am not an expert in using automake tools (Personally I use CMake build tool.)
Do you have any information about the patches?

As I am an old user of osdlyrics, it is glad to see that I can contribute to the project.

**Comment by PedroHLC** [comment]
> Do you have any information about the patches?

I only took a look at the launchpad page (and they use the src form Debian) and the last change's diff include changes to Makefiles, so I imagine there is more, but I'm rushing with other things right now and don't have time to learn .deb's source-packages.

**Comment by chris4540** [comment]
Hi,
After a shallow investigation, I found it is not easy to fix.

First, `dist-packages` seems to be only used on Debian platform.
https://unix.stackexchange.com/questions/351394/makefile-installing-python-module-out-of-of-pythonpath

And it is also a bug of `python3-defaults` package.
https://bugs.launchpad.net/ubuntu/+source/python3-defaults/+bug/1408092

Here I can make up some solution:
1. Write a documentation to suggest user manually make a symbolic link from `site-packages` to `dist-packages`
2. For deb user, suggest to use python2
3. If the user using ubuntu 20.04, just install it from apt repository.
